### ISSUE TITLE
"/Surveys/survey_functions.php should no longer be included in custom code"

### ISSUE THREAD

**Issue by iznaut** [susom/redcap-em-public-survey-dag#1]
Hi @123andy - we had some users interested in this module, so I enabled it on a test project to check it out. After enabling, this message pops up at the top of the page:

> It appears that a REDCap hook, plugin, or external module on this page is including/requiring a PHP file in REDCap that is no longer used as of REDCap v9.8.0 and higher (although it still exists temporarily). Please note that the files listed below will cease to be a part of the REDCap base code in releases after May 2020, after which the code on this page may fail and may cause an error. You should notify your REDCap administrator and/or the hook/plugin/module author regarding this information so that the custom PHP code may be fixed accordingly. The following files below should no longer be included/required in PHP custom code: /Surveys/survey_functions.php.

Any plans to update in the near future? Thanks!

**Comment by 123andy** [comment]
We will support.  Haven't moved to 9.8 yet.  Thanks for letting me know.  I'll scan our code for survey functions push updates.

Thx,

-Andy

**Comment by 123andy** [comment]
@izneuhaus - we just pushed 1.0.3 which removes the survey_functions.php to the repo.  Should be available shortly.
