### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by harpsicord86** [susom/redcap-em-public-survey-dag#4]
Hi there,

My workplace currently uses this external module in their REDCap installation and our IT department is looking to upgrade REDCap to v13 which uses PHP8. I just wondered if there is any plan to make this EM PHP8 compatible? Or is it already?

Thanks

**Comment by 123andy** [comment]
We haven't moved to php8 but plan to in about 1-2 months.  I would recommend testing it -- report any issues (or make a PR) and we can release a new version.
